# base image derivation 
FROM nvcr.io/nvidia/pytorch:21.08-py3

# timezone handler 
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris 

# initial system requirements 
RUN apt-get update --fix-missing && \
    apt-get install --yes --no-install-recommends \
        tzdata apt-utils dialog gcc git curl pkg-config build-essential ffmpeg 

# user creation 
RUN useradd --gid root --create-home solver 
WORKDIR /home/solver 

# virtualenv 
ENV VIRTUAL_ENV=/opt/venv 
RUN chmod -R g+rwx /home/solver && python -m venv $VIRTUAL_ENV --system-site-packages 
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# python requirements 

#### Default Settings
# RUN pip install --upgrade pip && \
#     pip install torchtext torchvision spacy pyzmq click loguru sentence_transformers rich pandas && \
#     pip install ftfy regex git+https://github.com/openai/CLIP.git && \
#     python -m spacy download en_core_web_sm

#### Good, but no support for 40xx gpus
# RUN pip install --upgrade pip && \
#     pip install torch==1.9.0 torchvision==0.10.0 torchtext==0.10.0 spacy==3.1.0 pyzmq==22.2.1 click==7.1.2 loguru==0.5.3 sentence_transformers==2.1.0 rich==10.5.0 pandas==1.3.1 && \
#     pip install ftfy==6.0.3 regex==2021.7.6 git+https://github.com/openai/CLIP.git && \
#     python -m spacy download en_core_web_sm

#### retry
RUN pip install --upgrade pip && \
    pip install torch==2.0.1 torchvision==0.15.2 torchtext==0.15.2 spacy==3.5.1 pyzmq==22.2.1 click==8.0.1 loguru==0.5.3 sentence_transformers==2.1.0 rich==10.5.0 pandas==1.3.1 && \
    pip install ftfy==6.0.3 regex==2021.7.6 git+https://github.com/openai/CLIP.git && \
    python -m spacy download en_core_web_sm

# pull source code 
COPY . ./ 

# env variables
ENV IMAGES='images/' 
ENV SOURCE='source/'
ENV TARGET='target/'
ENV MODELS='models/'

# entrypoint 
ENTRYPOINT ["python", "main.py"]
CMD ["--debug"]